-- DROP DATABASE CMS;
 CREATE DATABASE CMS;
 USE CMS;
CREATE TABLE [User]
(
	Username VARCHAR(50) PRIMARY KEY,
	[Name] VARCHAR(50),
	Email VARCHAR(50),
	[Password] VARCHAR(50)
);

CREATE TABLE Deadline
(
	DeadlineID INT PRIMARY KEY,
	ProposalDeadline DATE,
	AbstractDeadline DATE
);

CREATE TABLE [Event]
(
	EventID INT PRIMARY KEY,
	Interval VARCHAR(50),
	DeadlineID INT UNIQUE FOREIGN KEY REFERENCES Deadline(DeadlineID)
);

CREATE TABLE PCMembers
(
	PCID INT PRIMARY KEY,
	EventID INT FOREIGN KEY REFERENCES [Event](EventID),
	Username VARCHAR(50) UNIQUE FOREIGN KEY REFERENCES [User](Username)
);

CREATE TABLE SessionChair
(
	SessionChairID INT PRIMARY KEY,
	PCID INT UNIQUE FOREIGN KEY REFERENCES PCMembers(PCID)
);

CREATE TABLE Section
(
	SectionID INT PRIMARY KEY,
	SessionChairID INT UNIQUE FOREIGN KEY REFERENCES SessionChair(SessionChairID),
	EventID INT FOREIGN KEY REFERENCES Event(EventID),
	[Name] VARCHAR(50)
);

CREATE TABLE Author
(
	AuthorID INT PRIMARY KEY,
	Username VARCHAR(50) UNIQUE FOREIGN KEY REFERENCES [User](Username)
);

CREATE TABLE Proposal
(
	ProposalID INT PRIMARY KEY, 
	[Name] VARCHAR(50),
	Keyword VARCHAR(50),
	Topic VARCHAR(50),
	Metainfo VARCHAR(50)
);

CREATE TABLE Abstract
(
	AbstractID INT PRIMARY KEY,
	Title VARCHAR(50),
	[Name] VARCHAR(50), 
	Purpose VARCHAR(100),
	Methods VARCHAR(100)
);

CREATE TABLE Paper
(
	PaperID INT PRIMARY KEY,
	ProposalID INT UNIQUE FOREIGN KEY REFERENCES Proposal(ProposalID),
	AbstractID INT UNIQUE FOREIGN KEY REFERENCES Abstract(AbstractID)
);

CREATE TABLE Writes
(
	WritesID INT PRIMARY KEY, 
	AuthorID INT FOREIGN KEY REFERENCES Author(AuthorID),
	PaperID INT FOREIGN KEY REFERENCES Paper(PaperID)
);

CREATE TABLE Speaker
(
	SpeakerID INT PRIMARY KEY,
	SectionID INT FOREIGN KEY REFERENCES Section(SectionID),
	AuthorID INT UNIQUE FOREIGN KEY REFERENCES Author(AuthorID)
);

CREATE TABLE [Listener]
(
	ListenerID INT PRIMARY KEY,
	Username VARCHAR(50) UNIQUE FOREIGN KEY REFERENCES [User](Username),
	SectionID INT FOREIGN KEY REFERENCES Section(SectionID)
);

CREATE TABLE Chair
(
	ChairID INT PRIMARY KEY,
	PCID INT UNIQUE FOREIGN KEY REFERENCES PCMembers(PCID),
	isCoChair INT
);

CREATE TABLE Reviewer
(
	ReviewerID INT PRIMARY KEY,
	Username VARCHAR(50) UNIQUE FOREIGN KEY REFERENCES [User](Username)
);

CREATE TABLE Recommendations
(
	RecommID INT PRIMARY KEY,
	ReviewerID INT FOREIGN KEY REFERENCES Reviewer(ReviewerID),
	PaperID INT UNIQUE FOREIGN KEY REFERENCES Paper(PaperID),
	Comment VARCHAR(200)
);


